### ISSUE TITLE
Publish on OpenUPM

### ISSUE THREAD

**Issue by favoyang** [locus84/Locus-Bundle-System#1]
Hi @locus84 ,

Thanks for creating the awesome project, very interesting intention. I'd like to include it to the [OpenUPM platform](https://www.openupm.com/), an open source Unity package registry with automatic build pipelines that bundle UPM package based on semver git tags. Here's the [announcement blog](https://medium.com/openupm/openupm-beta-is-now-available-a6665ff60c71) for more details.

Your package is well structured, the only thing missed is a GitHub release (git tag, like 1.0.0 / v1.0.0). 
- The easier way is to create release manually via GitHub releases page.
- Or use [semantic-release](https://medium.com/openupm/how-to-maintain-upm-package-part-2-f352fbf5f87c) to automate it (but it requires you change your commit message style).

Thought?

Update: fixed the semantic-release link

**Comment by locus84** [comment]
Hi there @favoyang.

Guess I already have tags for release(missed 1.0.2.. oops).
You can add this repo to OpenUPM anytime.(Great vision btw!)

I'm rather new to automation stuffs and git workflow itself 😄 .
So I'll read your articles thoroughly and will try to implement later(in a day or two?)!

Thank you!

**Comment by favoyang** [comment]
Hi @locus84,

The package is available at https://openupm.com/packages/com.locus.bundlesystem/. I prepared documentation update 
https://github.com/locus84/Locus-Bundle-System/pull/2, please consider to merge.

I will close this issue as it's been solved. But feel free to continue the conversation if you find any issues about the GitHub actions.

**Comment by locus84** [comment]
Hi there, I've fix an compatibility issue that my friend found.
And taged as 1.0.3, how can I update openUPM as 1.0.3?
(Cuz now i'm using openupm as default :D)

**Comment by favoyang** [comment]
Build pipelines watch the build list every 5 mins (I'm considering to speed up to 3 mins).  See the build result at the Build Issues section.

https://openupm.com/packages/com.locus.bundlesystem/

![image](https://user-images.githubusercontent.com/125390/73901498-ef639d80-48cd-11ea-8bf3-70e82172cf36.png)

The issue of 1.0.3 is version conflict. You need bump package.json version and re-tag to fix it.

Well that's one reason to deploy the semantic-release bot.

**Comment by locus84** [comment]
I see what's wrong. Anyway it's easier than I expected.
Thank you!
