### ISSUE TITLE
Cannot initialize on Android

### ISSUE THREAD

**Issue by melih-veloxia** [locus84/Locus-Bundle-System#11]
**How to reproduce:**
1- Import files into /Packages / install via git url from UPM
2- Create Build Settings file
3- Fill the settings
4- Build both local & remote
4- Build player

**Unity Console log after building player:** 
`A meta data file (.meta) exists but its asset 'Assets/StreamingAssets/localbundles' can't be found. When moving or deleting files outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.
UnityEditor.AssetDatabase:Refresh ()
BundleSystem.AssetbundleBuildProcessors:OnPostprocessBuild (UnityEditor.Build.Reporting.BuildReport) (at Packages/Locus-Bundle-System-1.1.5/Editor/AssetbundleBuildProcessors.cs:46)
UnityEngine.GUIUtility:ProcessEvent (int,intptr)`

**Config File:**
<img width="501" alt="Screen Shot 2021-04-01 at 16 59 03" src="https://user-images.githubusercontent.com/67944801/113305525-cb51ef80-930b-11eb-8878-f4d53321e69e.png">

**Problem:**
Cannot initialize BunleManager & cannot load local bundles. On Editor & iOS, everything works fine. Tried reimporting all assets, reinstalling everything related with the Bundle System.
<img width="900" alt="Screen Shot 2021-04-01 at 17 03 12" src="https://user-images.githubusercontent.com/67944801/113305994-46b3a100-930c-11eb-83a9-f7349a72fe09.png">

**Comment by locus84** [comment]
Will look into it

**Comment by locus84** [comment]
Can you give me BundleErrorCode in BundleAsyncOperation which returned by initialize function?

**Comment by melih-veloxia** [comment]
`NotFinished
UnityEngine.Logger:Log(LogType, Object)
{ScriptName}.<Start>d__4:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
`

**Comment by locus84** [comment]
KK that's enough information thanks

**Comment by locus84** [comment]
It looks like android does not squash multiple '/' character into one when there're in the path.
Fixed/Tested on my machine.
Please try 1.1.6

**Comment by melih-veloxia** [comment]
Yes it is fixed now with 1.1.6. Thank you!
