### ISSUE TITLE
Error with Domain Reload disabled (Enter Play Mode options)

### ISSUE THREAD

**Issue by andreiagmu** [locus84/Locus-Bundle-System#17]
In my project, I prefer to work with Unity's Domain Reload disabled, for MUCH faster play mode tests/iterations.
But this is causing an error with Locus Bundle System (explained below).
I'm testing the bundles in Windows platform, with Emulate in Editor = true.

I set my Play Mode options like this:
Project Settings -> Editor -> Enter Play Mode Options (enabled)
Reload Domain is disabled, Reload Scene is enabled

With the settings above (Domain Reload disabled), when I enter Play Mode, it seems Locus Bundle System isn't initialized, and then I get [Bundle you requested could not be found] errors.
If Reload Domain is enabled (or if Enter Play Mode Options is disabled), Locus Bundle System is initialized correctly and the bundles load correctly.

Is Locus Build System not compatible with disabling Domain Reload? Can you add this compatibility?

**Comment by andreiagmu** [comment]
Related documentation:
https://docs.unity3d.com/Manual/DomainReloading.html

**Comment by locus84** [comment]
Thank you, I'll look into it. looks like a necessary functionality.

**Comment by andreiagmu** [comment]
This issue was fixed in v1.1.9. Thanks!
