### ISSUE TITLE
[Bug] "Get Expected Sharedbundle List" operation makes scene lose prefab references

### ISSUE THREAD

**Issue by andreiagmu** [locus84/Locus-Bundle-System#18]
Using Locus Bundle System v1.1.8.
Issue detected in Unity 2020.3.14f1 and 2021.1.14f1. 
My OS is Windows 10.

After "Get Expected Sharedbundle List" finishes its operation, I click Confirm to close the "Succeeded!" popup.
Then, it loads a scene that may not necessarily be the last scene I was working on, I guess it loads the last scene that was scanned in the bundles. (this is already a minor issue)

But if that scene had prefab instances, after the "Succeeded!" popup closes, the scene loses all its prefab links. (!)

At this state, if the user opens another scene, then opens that earlier scene again, the prefab links return to normal.
But if the user instead make some changes in the scene and save it, the "lost prefab links" will be also saved. (!)
Next time(s) the user opens the saved scene, it won't have any prefab links.

**Comment by locus84** [comment]
Oh that's quite a problem. The scan function itself is from part of scriptable build pipline so I think I just should remember last opened main scene, and get back to there after it's done. Thank you!

**Comment by andreiagmu** [comment]
The mentioned issues were fixed in v1.1.9. Thanks!
