### ISSUE TITLE
Material color don't change in prefab

### ISSUE THREAD

**Issue by m64s** [locus84/Locus-Bundle-System#20]
Hello Locus, when I change the color of the main material (from Assets folder direct) used in the prefab, it does not change in the prefab when I instantiate it (in Editor it works but on android does not work), how can I fix it?

**Comment by locus84** [comment]
Hello, you should rebuild your local bundles before build if you have some changes, you can make an editor script that builds local bundles automatically whenever you want to build.

**Comment by m64s** [comment]
Thanks for the quick reply, yes I rebuild the local bundles every time before I build the game, But what I think is that when I Instantiate the prefab from your bundle system, it creates its own material so when I change material color from the script the prefab has its own material not from the main material that exists in Assets/Materials folder

**Comment by m64s** [comment]
![IMG_20220221_083532](https://user-images.githubusercontent.com/68363209/154895718-b26fe256-d4b0-4225-a56c-acffcf413754.png)


Here the blue one I instantiate it by your bundle system, and the orange one by default way.

When the game awake the main material color changed from blue to orange (from script) as you see that I instantiate it by default way it has changed color but the other dont

**Comment by locus84** [comment]
Yes, the materials in build cannot be references by assetbundles, so as fonts, textures.. etc... bundles shares same resources among them, this is normal behaviour of unity assetbundle system.

**Comment by locus84** [comment]
And beware if you change some properties using scripts they will be duplicated by the engine.

**Comment by m64s** [comment]
So how I can fix it? 

I dont want to change all prefab material color for each, I just want to change the reference, because I have multi prefabs that use the same material.

**Comment by locus84** [comment]
1. By setting same marterial in runtime.
2. Reference SharedMaterial and change color(but all instantiated object should be same origin - assetbundle or normal resource)
3. https://docs.unity3d.com/ScriptReference/Shader.SetGlobalVector.html

**Comment by m64s** [comment]
Thanks for your advice, I added the material to the assetbundle and then reference it using the assetbundle and load it by `BundleManager.Load<Material>()` then I changed the color and now its work fine for all prefab that I instantiate it from assetbundle only and this is fine to me.
