### ISSUE TITLE
Corrupted files

### ISSUE THREAD

**Issue by chebedzic** [locus84/Locus-Bundle-System#22]
Hi there,
We are using your bundle system, but we bumped into an issue while using it, We have a couple of scriptable objects which hold the references to certain sprites/prefabs.

We load those scriptable objects from time to time, but sometimes(not always)
 we bumb into an issue:
 
E/Unity: The file 'none' is corrupted! Remove it and launch unity again!
    [Position out of bounds!]
    UnityEngine.Object:Instantiate(Object, Transform, Boolean)
    UnityEngine.Object:Instantiate(T, Transform, Boolean)
    ****:Awake()
    
    And inside that awake there is a line BundleSystem.BundleManager.Load<T>(bundleName, eventName), which loads scriptable object, of type T,  that has a field that points towards a prefab.
    
Sometimes that prefab ends up being corrupted, sometimes it's not corrupted.

After this we are followed by a fatal signal and a crash:
-Fatal signal 5 (SIGTRAP), code -6 (SI_TKILL) in tid 9865 (UnityMain), pid....

**Comment by locus84** [comment]
did you load scriptable object and instantiate?
did you change properties of those scriptable object while using it?

**Comment by chebedzic** [comment]
No instantiation is done we just load them from the bundles they actually keep references to images and sprites that are needed for our internal skinning system.

Also the things i forgot to mention.
-It works fine in editor, even with emulate checkbox
-It doesn't work on android.
-Flow is sceneload(not the first scene)-> on awake of a certain component, scriptable objects are loaded-> prefab from a property of scriptable object is instantiated.
-Also when i said it sometimes work and sometimes its corrupted, i meant in the same build, the same assets, it sometimes work, and sometimes it doesn't work.

Scriptable object is not changed at all dring the process, since we use them as reference holders.

**Comment by locus84** [comment]
do you use auto release feature?? if so, the asset's which have your own reference via scriptable object will not be reference counted. you must load individually or keep scriptable object forever to prevent the source bundle automatically released.
Or, you can disable this feature and use Resource.UnloadUnusedAssets() function.

https://github.com/locus84/Locus-Bundle-System/blob/bc8d911dfd4318631d71e5dd160eacd1dd53c389/Runtime/BundleManager.cs#L129

**Comment by chebedzic** [comment]
Yeah when autoReloadBundle = false, we don't face the same issue, but issue seems to be if two scriptable objects have the same shared asset, when one is unloaded, and the other one is loaded at the same time.
