### ISSUE TITLE
s_AssetBundles clearing

### ISSUE THREAD

**Issue by chebedzic** [locus84/Locus-Bundle-System#24]
https://github.com/locus84/Locus-Bundle-System/blob/bc8d911dfd4318631d71e5dd160eacd1dd53c389/Runtime/BundleManager.cs#L471-L479

As far as i can see initialising bundles inside CoInitalizeLocalBundles, fills in dictionary s_AssetBundles, which is fine, but every time i try to download a bundle and specify which bundle i want, the other bundles are dropped from the memory.

Well our code looks like:
-Initialise all bundles including local bundles.
-Download just the bundles that we need for now.
-Downloading procedure drops other bundles, also drops local bundles from the dictionary.

**Comment by locus84** [comment]
Yes the subsetNames parameter of the download function must contain entire list you need, you have to keep track names you need to load yourself. In that way, you can unload things that you don't need to use at that moment. It's intended.

**Comment by chebedzic** [comment]
So initialize loads up all of the local bundles and adds them to s_AssetBundles?

But using the DownloadAssetBundles, without passing all of the local bundles as params, would drop the local bundles out of s_AssetBundles, and make them unusable? Thats intended?

**Comment by chebedzic** [comment]
sorry for closing and reopening missclicked
