### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by AsheshPlays** [locus84/Locus-Bundle-System#25]
1. Does this need advanced knowledge to use?
2. Mobile Supported?
3. Does it have Patcher ?
4. Does it support Hot-Fix patches?

**Comment by locus84** [comment]
1. basic knowledge about unity3d's assetbundle system is needed.
2. this is for mobile. for desktop, I recommand other solutions.
3. It does not have explicit patcher, as all mobile game does.
4. You can't update binaries of you application in mobile with assetbundle.
